### ISSUE TITLE
Email validation regex does not validate emails with new domain endings

### ISSUE THREAD

**Issue by davleh** [interactive-pioneers/iptools-jquery-validator#17]
Mail regex only allows domain endings with 2 to 4 characters, should allows also more than 4 characters.
Regex can be improved generally.

**Comment by ain** [comment]
The problem with the regex is, since I've dealt with it a lot, **there's no perfect email regex**. 

We've had cases where clients come with their own regexes that are completely flawed. And change it regularly. 

I'd suggest deploying a very generic regex, e.g. the one used by Rails. I think it'd be a good compromise.
