### ISSUE TITLE
Using 'validateOnCustomEvent' option runs into race condition 

### ISSUE THREAD

**Issue by beroes** [interactive-pioneers/iptools-jquery-validator#20]

**Comment by beroes** [comment]
Current: The form has been submited despite of custom event being populated.
Expected: The component should prevent form submition until custom event has not been emmited.

**Comment by ain** [comment]
There need to be *tests* against this behaviour as well.

**Comment by ain** [comment]
No race condition confirmed. It's expected behaviour with both, validation on submit, and validation on custom eventm work together, but submit prevails. It is expected behaviour and should be considered on implementation.

#31 will resolve scenarios where submission needs to be manually triggered after custom event based validation completes.
